version: 7.57.{build}.0
image: Visual Studio 2015


clone_depth: 1

platform:
    - x64

configuration:
    - Unicode Release

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    verbosity: minimal

build_script:
    - cd c:\projects\notepad-plus-plus\scintilla\win32
    - if "%configuration%"=="Unicode Debug" set scintilla_debug=DEBUG=1
    - if "%configuration%"=="Unicode Release" set scintilla_debug=
    - nmake NOBOOST=1 %scintilla_debug% -f scintilla.mak
    - cd c:\projects\notepad-plus-plus\PowerEditor\visual.net\
    - msbuild notepadPlus.vcxproj /p:configuration="%configuration%" /p:platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild notepadPlus.vcxproj /p:configuration="%configuration%" /p:platform=Win32 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd c:\projects\notepad-plus-plus\
    - ps: >-
        $nppx64FileName = "Notepad++.x64.$env:CONFIGURATION.exe"
        $nppw32FileName = "Notepad++.Win32.$env:CONFIGURATION.exe"

        if ($env:CONFIGURATION -eq "Unicode Release") {
            Push-AppveyorArtifact "PowerEditor\bin64\Notepad++.exe" -FileName "$nppx64FileName"
            Push-AppveyorArtifact "PowerEditor\bin\Notepad++.exe" -FileName "$nppw32FileName"
        }

        if ($env:CONFIGURATION -eq "Unicode Debug") {
            Push-AppveyorArtifact "PowerEditor\visual.net\x64\Unicode Debug\Notepad++.exe" -FileName "$nppx64FileName"
            Push-AppveyorArtifact "PowerEditor\visual.net\Unicode Debug\Notepad++.exe" -FileName "$nppw32FileName"
        }

        Push-AppveyorArtifact "scintilla\bin\SciLexer.dll" -FileName "SciLexer.$env:CONFIGURATION.dll"
