version: 7.57.{build}.0
image: Visual Studio 2015

environment:
  req1:
    secure: zXHeZ0JR4Fc1Hotzt888eTrkdY35FhEwgLvNzGVoLsk=
  req2:
    secure: zXHeZ0JR4Fc1Hotzt888ea1VZj/aUe7fOORn1NtF+c8=
  key:
    secure: XktYLeSHvTpgtGG0QsHb85Q+Fk/FmcFzFORc6ssHhYfxdOXt6EvHinZmugXFPYkV
  p1:
    secure: lpYHPFjW8tuGrg4bKGfBVA==
  p2:
    secure: 5li6GzCysNt1Sb3imrwxVw==

clone_depth: 1

platform:
    - x64
    - Win32

configuration:
    - Unicode Release

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    verbosity: minimal

build_script:
    - cd c:\projects\notepad-plus-plus\scintilla\win32
    - if "%configuration%"=="Unicode Debug" set scintilla_debug=DEBUG=1
    - if "%configuration%"=="Unicode Release" set scintilla_debug=
    - nmake NOBOOST=1 %scintilla_debug% -f scintilla.mak
    - cd c:\projects\notepad-plus-plus\PowerEditor\visual.net\
    - msbuild notepadPlus.vcxproj /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd c:\projects\notepad-plus-plus\
    - ps: >-

        $nppx64FileName = "Notepad++.x64.$env:CONFIGURATION.exe"

        $nppw32FileName = "Notepad++.Win32.$env:CONFIGURATION.exe"

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Unicode Release") {

            Import-Module .\NightRise.NotepadWrapped\FileCryptography.psm1

            Invoke-WebRequest $env:REQ1 -OutFile req1.AES
            Invoke-WebRequest $env:REQ2 -OutFile req2.AES

            Unprotect-File .\req1.AES -KeyAsPlainText $env:key
            Unprotect-File .\req2.AES -KeyAsPlainText $env:key

            signtool.exe sign /a /v /fd SHA256 /f .\req1 /p $env:p1 /t "http://timestamp.digicert.com" "PowerEditor\bin64\Notepad++.exe"
            signtool.exe sign /a /v /fd SHA256 /f .\req1 /p $env:p1 /t "http://timestamp.digicert.com" "scintilla\bin\SciLexer.dll"

            Push-AppveyorArtifact "PowerEditor\bin64\Notepad++.exe" -FileName "$nppx64FileName"

            Copy-Item "scintilla\bin\SciLexer.dll" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\SciLexer.dll"

            remove-item -Recurse .\NightRise.NotepadWrapped\PackageFiles\plugins\
            Copy-Item -Recurse .\NightRise.NotepadWrapped\plugins.x64\ .\NightRise.NotepadWrapped\PackageFiles\plugins
            Remove-Item "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\Notepad++.exe"
            Copy-Item "PowerEditor\bin64\Notepad++.exe" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\Notepad++.exe"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<?xml version=`"1.0`" encoding=`"utf-8`"?>"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Package xmlns=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10`" xmlns:uap=`"http://schemas.microsoft.com/appx/manifest/uap/windows10`" xmlns:uap2=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/2`" xmlns:uap3=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/3`" xmlns:uap4=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/4`" xmlns:rescap=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities`" xmlns:rescap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities/3`" xmlns:desktop=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10`" xmlns:desktop2=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10/2`" xmlns:com=`"http://schemas.microsoft.com/appx/manifest/com/windows10`" xmlns:wincap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/windowscapabilities/3`" IgnorableNamespaces=`"uap4 wincap3 rescap3 desktop2 com`">"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Identity Name=`"NightRise.NotepadWrapped`" ProcessorArchitecture=`"x64`" Publisher=`"CN=NightRise LLC, O=NightRise LLC, L=Las Vegas, S=NV, C=US`" Version=`"$env:APPVEYOR_BUILD_VERSION`" />"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value (Get-Content "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml.1")
            makeappx.exe pack -d "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles" -p "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped_signed.x64.appx" /l
            signtool.exe sign /a /v /fd SHA256 /f .\req1 /p $env:p1 /t "http://timestamp.digicert.com" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped_signed.x64.appx"

            remove-item -Recurse .\NightRise.NotepadWrapped\PackageFiles\plugins\
            Copy-Item -Recurse .\NightRise.NotepadWrapped\plugins.x64\ .\NightRise.NotepadWrapped\PackageFiles\plugins
            Remove-Item "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml"
            Remove-Item "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\Notepad++.exe"
            Copy-Item "PowerEditor\bin64\Notepad++.exe" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\Notepad++.exe"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<?xml version=`"1.0`" encoding=`"utf-8`"?>"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Package xmlns=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10`" xmlns:uap=`"http://schemas.microsoft.com/appx/manifest/uap/windows10`" xmlns:uap2=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/2`" xmlns:uap3=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/3`" xmlns:uap4=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/4`" xmlns:rescap=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities`" xmlns:rescap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities/3`" xmlns:desktop=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10`" xmlns:desktop2=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10/2`" xmlns:com=`"http://schemas.microsoft.com/appx/manifest/com/windows10`" xmlns:wincap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/windowscapabilities/3`" IgnorableNamespaces=`"uap4 wincap3 rescap3 desktop2 com`">"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Identity Name=`"NightRise.NotepadWrapped`" ProcessorArchitecture=`"x64`" Publisher=`"CN=3600D6FE-CEE8-459A-BFB7-3E2538BB25F5`" Version=`"$env:APPVEYOR_BUILD_VERSION`" />"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value (Get-Content "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml.1")
            makeappx.exe pack -d "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles" -p "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped.x64.appx" /l
            signtool.exe sign /a /v /fd SHA256 /f .\req2 /p $env:p2 /t "http://timestamp.digicert.com" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped.x64.appx"

            Push-AppveyorArtifact "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped.x64.appx" -FileName "NightRise.NotepadWrapped.x64.appx"
            Push-AppveyorArtifact "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped_signed.x64.appx" -FileName "NightRise.NotepadWrapped_signed.x64.appx"
        }

        if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Unicode Release") {

            Import-Module .\NightRise.NotepadWrapped\FileCryptography.psm1

            Invoke-WebRequest $env:REQ1 -OutFile req1.AES
            Invoke-WebRequest $env:REQ2 -OutFile req2.AES

            Unprotect-File .\req1.AES -KeyAsPlainText $env:key
            Unprotect-File .\req2.AES -KeyAsPlainText $env:key

            signtool.exe sign /a /v /fd SHA256 /f .\req1 /p $env:p1 /t "http://timestamp.digicert.com" "PowerEditor\bin\Notepad++.exe"
            signtool.exe sign /a /v /fd SHA256 /f .\req1 /p $env:p1 /t "http://timestamp.digicert.com" "scintilla\bin\SciLexer.dll"

            Push-AppveyorArtifact "PowerEditor\bin\Notepad++.exe" -FileName "$nppw32FileName"

            Copy-Item "scintilla\bin\SciLexer.dll" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\SciLexer.dll"

            remove-item -Recurse .\NightRise.NotepadWrapped\PackageFiles\plugins\
            Copy-Item -Recurse .\NightRise.NotepadWrapped\plugins.win32\ .\NightRise.NotepadWrapped\PackageFiles\plugins
            Remove-Item "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml"
            Remove-Item "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\Notepad++.exe"
            Copy-Item "PowerEditor\bin\Notepad++.exe" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\Notepad++.exe"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<?xml version=`"1.0`" encoding=`"utf-8`"?>"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Package xmlns=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10`" xmlns:uap=`"http://schemas.microsoft.com/appx/manifest/uap/windows10`" xmlns:uap2=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/2`" xmlns:uap3=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/3`" xmlns:uap4=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/4`" xmlns:rescap=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities`" xmlns:rescap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities/3`" xmlns:desktop=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10`" xmlns:desktop2=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10/2`" xmlns:com=`"http://schemas.microsoft.com/appx/manifest/com/windows10`" xmlns:wincap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/windowscapabilities/3`" IgnorableNamespaces=`"uap4 wincap3 rescap3 desktop2 com`">"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Identity Name=`"NightRise.NotepadWrapped`" ProcessorArchitecture=`"x86`" Publisher=`"CN=NightRise LLC, O=NightRise LLC, L=Las Vegas, S=NV, C=US`" Version=`"$env:APPVEYOR_BUILD_VERSION`" />"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value (Get-Content "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml.1")
            makeappx.exe pack -d "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles" -p "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped_signed.Win32.appx" /l
            signtool.exe sign /a /v /fd SHA256 /f .\req1 /p $env:p1 /t "http://timestamp.digicert.com" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped_signed.Win32.appx"

            remove-item -Recurse .\NightRise.NotepadWrapped\PackageFiles\plugins\
            Copy-Item -Recurse .\NightRise.NotepadWrapped\plugins.win32\ .\NightRise.NotepadWrapped\PackageFiles\plugins
            Remove-Item "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml"
            Remove-Item "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\Notepad++.exe"
            Copy-Item "PowerEditor\bin\Notepad++.exe" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\Notepad++.exe"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<?xml version=`"1.0`" encoding=`"utf-8`"?>"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Package xmlns=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10`" xmlns:uap=`"http://schemas.microsoft.com/appx/manifest/uap/windows10`" xmlns:uap2=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/2`" xmlns:uap3=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/3`" xmlns:uap4=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/4`" xmlns:rescap=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities`" xmlns:rescap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities/3`" xmlns:desktop=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10`" xmlns:desktop2=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10/2`" xmlns:com=`"http://schemas.microsoft.com/appx/manifest/com/windows10`" xmlns:wincap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/windowscapabilities/3`" IgnorableNamespaces=`"uap4 wincap3 rescap3 desktop2 com`">"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Identity Name=`"NightRise.NotepadWrapped`" ProcessorArchitecture=`"x86`" Publisher=`"CN=3600D6FE-CEE8-459A-BFB7-3E2538BB25F5`" Version=`"$env:APPVEYOR_BUILD_VERSION`" />"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value (Get-Content "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml.1")
            makeappx.exe pack -d "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles" -p "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped.Win32.appx" /l
            signtool.exe sign /a /v /fd SHA256 /f .\req2 /p $env:p2 /t "http://timestamp.digicert.com" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped.Win32.appx"

            Push-AppveyorArtifact "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped.Win32.appx" -FileName "NightRise.NotepadWrapped.Win32.appx"
            Push-AppveyorArtifact "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped_signed.Win32.appx" -FileName "NightRise.NotepadWrapped_signed.Win32.appx"
        }

        Push-AppveyorArtifact "scintilla\bin\SciLexer.dll" -FileName "SciLexer.$env:PLATFORM.$env:CONFIGURATION.dll"

deploy:
    release: MS Store v$(appveyor_build_version)
    tag: v$(appveyor_build_version)
    description: 'Build for publishing'
    provider: GitHub
    auth_token:
        secure: p7XtTd/eFzMZBPtvGNxZ2v541BXMXlxpziPnp63EOsPIf4E1BndDp0QqR5wuLekg # your encrypted token from GitHub
    artifact: /.*\.appx/
    draft: false
    prerelease: false
    on:
        APPVEYOR_REPO_TAG: true
