version: 7.57.{build}.0
image: Visual Studio 2015


clone_depth: 1

platform:
    - x64

configuration:
    - Unicode Release

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    verbosity: minimal

build_script:
    - cd c:\projects\notepad-plus-plus\scintilla\win32
    - if "%configuration%"=="Unicode Debug" set scintilla_debug=DEBUG=1
    - if "%configuration%"=="Unicode Release" set scintilla_debug=
    - nmake NOBOOST=1 %scintilla_debug% -f scintilla.mak
    - cd c:\projects\notepad-plus-plus\PowerEditor\visual.net\
    - msbuild notepadPlus.vcxproj /p:configuration="%configuration%" /p:platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild notepadPlus.vcxproj /p:configuration="%configuration%" /p:platform=Win32 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd c:\projects\notepad-plus-plus\
    - ps: >-
        $nppx64FileName = "Notepad++.x64.$env:CONFIGURATION.exe"

        $nppw32FileName = "Notepad++.Win32.$env:CONFIGURATION.exe"

        if ($env:CONFIGURATION -eq "Unicode Release") {
            Push-AppveyorArtifact "PowerEditor\bin64\Notepad++.exe" -FileName "$nppx64FileName"
            Push-AppveyorArtifact "PowerEditor\bin\Notepad++.exe" -FileName "$nppw32FileName"

            Copy-Item "PowerEditor\bin64\Notepad++.exe" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\Notepad++.exe"
            Copy-Item "scintilla\bin\SciLexer.dll" "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\SciLexer.dll"

            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<?xml version=`"1.0`" encoding=`"utf-8`"?>"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Package xmlns=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10`" xmlns:uap=`"http://schemas.microsoft.com/appx/manifest/uap/windows10`" xmlns:uap2=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/2`" xmlns:uap3=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/3`" xmlns:uap4=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/4`" xmlns:rescap=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities`" xmlns:rescap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities/3`" xmlns:desktop=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10`" xmlns:desktop2=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10/2`" xmlns:com=`"http://schemas.microsoft.com/appx/manifest/com/windows10`" xmlns:wincap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/windowscapabilities/3`" IgnorableNamespaces=`"uap4 wincap3 rescap3 desktop2 com`">"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Identity Name=`"NightRise.NotepadWrapped`" ProcessorArchitecture=`"x64`" Publisher=`"CN=NightRise LLC, O=NightRise LLC, L=Las Vegas, S=NV, C=US`" Version=`"$env:APPVEYOR_BUILD_VERSION`" />"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value (Get-Content "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml.1")
            Push-AppveyorArtifact "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -FileName "AppxManifest_signed.xml"
            makeappx.exe pack -d "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles" -p "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped_signed.appx" /l
            
            Remove-Item "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml"

            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<?xml version=`"1.0`" encoding=`"utf-8`"?>"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Package xmlns=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10`" xmlns:uap=`"http://schemas.microsoft.com/appx/manifest/uap/windows10`" xmlns:uap2=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/2`" xmlns:uap3=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/3`" xmlns:uap4=`"http://schemas.microsoft.com/appx/manifest/uap/windows10/4`" xmlns:rescap=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities`" xmlns:rescap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities/3`" xmlns:desktop=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10`" xmlns:desktop2=`"http://schemas.microsoft.com/appx/manifest/desktop/windows10/2`" xmlns:com=`"http://schemas.microsoft.com/appx/manifest/com/windows10`" xmlns:wincap3=`"http://schemas.microsoft.com/appx/manifest/foundation/windows10/windowscapabilities/3`" IgnorableNamespaces=`"uap4 wincap3 rescap3 desktop2 com`">"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value "<Identity Name=`"NightRise.NotepadWrapped`" ProcessorArchitecture=`"x64`" Publisher=`"CN=3600D6FE-CEE8-459A-BFB7-3E2538BB25F5`" Version=`"$env:APPVEYOR_BUILD_VERSION`" />"
            Add-Content -Path "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -Value (Get-Content "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml.1")
            Push-AppveyorArtifact "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles\AppxManifest.xml" -FileName "AppxManifest.xml"
            makeappx.exe pack -d "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\PackageFiles" -p "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped.appx" /l
            


            Push-AppveyorArtifact "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped.appx" -FileName "NightRise.NotepadWrapped.appx"
            Push-AppveyorArtifact "C:\projects\notepad-plus-plus\NightRise.NotepadWrapped\NightRise.NotepadWrapped_signed.appx" -FileName "NightRise.NotepadWrapped_signed.appx"

        }

        if ($env:CONFIGURATION -eq "Unicode Debug") {
            Push-AppveyorArtifact "PowerEditor\visual.net\x64\Unicode Debug\Notepad++.exe" -FileName "$nppx64FileName"
            Push-AppveyorArtifact "PowerEditor\visual.net\Unicode Debug\Notepad++.exe" -FileName "$nppw32FileName"
        }

        Push-AppveyorArtifact "scintilla\bin\SciLexer.dll" -FileName "SciLexer.$env:CONFIGURATION.dll"

deploy:
    release: MS Store v$(appveyor_build_version)
    description: 'Build for publishing'
    provider: GitHub
    auth_token:
        secure: p7XtTd/eFzMZBPtvGNxZ2v541BXMXlxpziPnp63EOsPIf4E1BndDp0QqR5wuLekg # your encrypted token from GitHub
    artifact: /.*\.appx/
    draft: false
    prerelease: true
    on:
        branch: master                   # release from master branch only
        appveyor_repo_tag: false        # deploy on tag push only
